# D.C. Properties - Preprocessing

This notebook pre-process the DC Properties dataset to extract the desired columns and prepare some of its datatypes. The selected columns are:

 * **NUM_UNITS** - Number of Units
 * **ROOMS** - Number of Rooms
 * **BEDRM** - Number of Bedrooms
 * **BATHRM** - Number of Full Bathrooms
 * **HF_BATHRM** - Number of Half Bathrooms (no bathtub or shower)
 * **KITCHENS** - Number of kitchens
 * **STORIES** - Number of stories in primary dwelling
 * **HEAT** - Heating
 * **AC** - Cooling
 * **FIREPLACES** - Number of fireplaces
 * **ROOF** - Roof type
 * **EXTWALL** - Exterior wall
 * **AYB** - The earliest time the main portion of the building was built
 * **EYB** - The year an improvement was built more recent than actual year built
 * **YR_SALE** - Year of most recent sale
 * **CNDTN** - Condition
 * **GBA** - Gross building area in square feet
 * **LANDAREA** - Land area of property in square feet
 * **WARD** - Ward (District is divided into eight wards, each with approximately 75,000 residents)
 * **X** - The longitude
 * **Y** - The latitude
 * **PRICE** - Price of most recent sale

## Imports and Config setting

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

## Data loading and Selection

Define a series of parameters that will be used in the notebook

In [3]:
# Params
input_data_path = '1_dc_properties_fixed_zipped.csv'
output_data_path = '2_dc_properties_processed_zipped.csv'
selected_cols = ['NUM_UNITS','ROOMS','BEDRM','BATHRM','HF_BATHRM','KITCHENS','STORIES','HEAT','AC','FIREPLACES','ROOF','EXTWALL','AYB','EYB','YR_SALE','CNDTN','GBA','LANDAREA','WARD', 'X', 'Y', 'PRICE']

Load the data and give a preview of it

In [4]:
data_df = pd.read_csv(input_data_path, low_memory=False, index_col=0, compression='zip')
data_df

,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,PRICE,QUALIFIED,SALE_NUM,GBA,BLDG_NUM,STYLE,STRUCT,GRADE,EXTWALL,ROOF,INTWALL,KITCHENS,FIREPLACES,USECODE,LANDAREA,GIS_LAST_MOD_DTTM,SOURCE,CMPLX_NUM,LIVING_GBA,FULLADDRESS,CITY,STATE,ZIPCODE,NATIONALGRID,LATITUDE,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT,YR_SALE,CNDTN
0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,1972,3.0,1095000.0,Q,1,2522.0,1,3 Story,Row Inside,Very Good,Common Brick,Metal- Sms,Hardwood,2.0,5,24,1680,2018-07-22 18:01:43,Residential,NaN,NaN,1748 SWANN STREET NW,WASHINGTON,DC,20009.0,18S UJ 23061 09289,38.914680,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,0152,-77.040429,38.914881,NW,2003.0,3.0
1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,1972,3.0,NaN,U,1,2567.0,1,3 Story,Row Inside,Very Good,Common Brick,Built Up,Hardwood,2.0,4,24,1680,2018-07-22 18:01:43,Residential,NaN,NaN,1746 SWANN STREET NW,WASHINGTON,DC,20009.0,18S UJ 23067 09289,38.914683,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,0152,-77.040429,38.914881,NW,2000.0,3.0
2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,1984,3.0,2100000.0,Q,3,2522.0,1,3 Story,Row Inside,Very Good,Common Brick,Built Up,Hardwood,2.0,4,24,1680,2018-07-22 18:01:43,Residential,NaN,NaN,1744 SWANN STREET NW,WASHINGTON,DC,20009.0,18S UJ 23074 09289,38.914684,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,0152,-77.040429,38.914881,NW,2016.0,4.0
3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,1984,3.0,1602000.0,Q,1,2484.0,1,3 Story,Row Inside,Very Good,Common Brick,Built Up,Hardwood,2.0,3,24,1680,2018-07-22 18:01:43,Residential,NaN,NaN,1742 SWANN STREET NW,WASHINGTON,DC,20009.0,18S UJ 23078 09288,38.914683,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,0152,-77.040429,38.914881,NW,2006.0,3.0
4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,1985,3.0,NaN,U,1,5255.0,1,3 Story,Semi-Detached,Very Good,Common Brick,Neopren,Hardwood,1.0,0,13,2032,2018-07-22 18:01:43,Residential,NaN,NaN,1804 NEW HAMPSHIRE AVENUE NW,WASHINGTON,DC,20009.0,18S UJ 23188 09253,38.914383,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,0152,-77.040429,38.914881,NW,NaN,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106672,2,0,Forced Air,N,2.0,8,4,1953.0,NaN,1962,2.0,NaN,U,1,1600.0,1,2 Story,Multi,Average,Common Brick,Built Up,Hardwood,2.0,0,23,6337,2018-07-22 18:01:43,Residential,NaN,NaN,123 JOLIET STREET SW,WASHINGTON,DC,20032.0,18S UH 25829 98897,38.821651,-77.006283,Congress Heights,016 A Congress Heights,10900.0,010900 2000,Ward 8,6254,-77.006347,38.821799,SW,NaN,2.0
106673,2,0,Forced Air,N,2.0,10,5,1953.0,NaN,1962,2.0,100000.0,U,1,1600.0,1,2 Story,Multi,Average,Common Brick,Built Up,Hardwood,2.0,0,23,5348,2018-07-22 18:01:43,Residential,NaN,NaN,127 JOLIET STREET SW,WASHINGTON,DC,20032.0,18S UH 25818 98885,38.821534,-77.006407,Congress Heights,016 A Congress Heights,10900.0,010900 2000,Ward 8,6254,-77.006347,38.821799,SW,2012.0,2.0
106674,2,0,Forced Air,N,2.0,10,4,1953.0,NaN,1953,2.0,NaN,U,1,1600.0,1,2 Story,Multi,Average,Common Brick,Built Up,Hardwood,2.0,0,23,3466,2018-07-22 18:01:43,Residential,NaN,NaN,131 JOLIET STREET SW,WASHINGTON,DC,20032.0,18S UH 25815 98879,38.821481,-77.006446,Congress Heights,016 A Congress Heights,10900.0,010900 2000,Ward 8,6254,-77.006347,38.821799,SW,2009.0,2.0
106675,2,0,Forced Air,N,2.0,10,4,1953.0,2017.0,1971,2.0,215000.0,U,4,1600.0,1,2 Story,Multi,Average,Common Brick,Comp Shingle,Hardwood,2.0,0,23,3046,2018-07-22 18:01:43,Residential,NaN,NaN,135 JOLIET STREET SW,WASHINGTON,DC,20032.0,18S UH 25807 98865,38.821356,-77.006528,Congress Heights,016 A Congress Heights,10900.0,010900 2000,Ward 8,6254,-77.006347,38.821799,SW,2017.0,3.0
106676,2,0,Forced Air,Y,2.0,10,4,1953.0,2018.0,1971,2.0,140000.0,U,2,1600.0,1,2 Story,Multi,Average,Common Brick,Comp Shingle,Hardwood,2.0,0,23,5098,2018-07-22 18:01:43,Residential,NaN,NaN,139 JOLIET STREET SW,WASHINGTON,DC,20032.0,18S UH 25804 98859,38.821300,-77.006571,Congress Heights,016 A Congress Heights,10900.0,010900 2000,Ward 8,6254,-77.006347,38.821799,SW,2017.0,4.0

Use the parameter of selected_cols to remove the undesired columns from out data.

In [5]:
# Filter the columns in the data
data_df = data_df[selected_cols]
data_df

,NUM_UNITS,ROOMS,BEDRM,BATHRM,HF_BATHRM,KITCHENS,STORIES,HEAT,AC,FIREPLACES,ROOF,EXTWALL,AYB,EYB,YR_SALE,CNDTN,GBA,LANDAREA,WARD,X,Y,PRICE
0,2.0,8,4,4,0,2.0,3.0,Warm Cool,Y,5,Metal- Sms,Common Brick,1910.0,1972,2003.0,3.0,2522.0,1680,Ward 2,-77.040429,38.914881,1095000.0
1,2.0,11,5,3,1,2.0,3.0,Warm Cool,Y,4,Built Up,Common Brick,1898.0,1972,2000.0,3.0,2567.0,1680,Ward 2,-77.040429,38.914881,NaN
2,2.0,9,5,3,1,2.0,3.0,Hot Water Rad,Y,4,Built Up,Common Brick,1910.0,1984,2016.0,4.0,2522.0,1680,Ward 2,-77.040429,38.914881,2100000.0
3,2.0,8,5,3,1,2.0,3.0,Hot Water Rad,Y,3,Built Up,Common Brick,1900.0,1984,2006.0,3.0,2484.0,1680,Ward 2,-77.040429,38.914881,1602000.0
4,1.0,11,3,2,1,1.0,3.0,Warm Cool,Y,0,Neopren,Common Brick,1913.0,1985,NaN,3.0,5255.0,2032,Ward 2,-77.040429,38.914881,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106672,2.0,8,4,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1962,NaN,2.0,1600.0,6337,Ward 8,-77.006347,38.821799,NaN
106673,2.0,10,5,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1962,2012.0,2.0,1600.0,5348,Ward 8,-77.006347,38.821799,100000.0
106674,2.0,10,4,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1953,2009.0,2.0,1600.0,3466,Ward 8,-77.006347,38.821799,NaN
106675,2.0,10,4,2,0,2.0,2.0,Forced Air,N,0,Comp Shingle,Common Brick,1953.0,1971,2017.0,3.0,1600.0,3046,Ward 8,-77.006347,38.821799,215000.0
106676,2.0,10,4,2,0,2.0,2.0,Forced Air,Y,0,Comp Shingle,Common Brick,1953.0,1971,2017.0,4.0,1600.0,5098,Ward 8,-77.006347,38.821799,140000.0

## Drop some nulls

The original raw data has been slightly cleaned and prepared. However, there are still some nulls that we might want to fix.

*Note: For now, you can ignore the nulls in PRICE and YR_SALE*

In [6]:
# Check the nulls per column
data_df.isnull().sum()

NUM_UNITS         0
ROOMS             0
BEDRM             0
BATHRM            0
HF_BATHRM         0
KITCHENS          1
STORIES          44
HEAT              0
AC                0
FIREPLACES        0
ROOF              0
EXTWALL           0
AYB             237
EYB               0
YR_SALE       22506
CNDTN             0
GBA               0
LANDAREA          0
WARD              1
X               237
Y               237
PRICE         48781
dtype: int64

In [7]:
# We drop the few properties that have some nulls in the following columns, they are not important
data_df = data_df.dropna(axis=0, subset=['KITCHENS', 'STORIES', 'AYB', 'WARD', 'X', 'Y'])

In [8]:
data_df.isnull().sum()

NUM_UNITS         0
ROOMS             0
BEDRM             0
BATHRM            0
HF_BATHRM         0
KITCHENS          0
STORIES           0
HEAT              0
AC                0
FIREPLACES        0
ROOF              0
EXTWALL           0
AYB               0
EYB               0
YR_SALE       22364
CNDTN             0
GBA               0
LANDAREA          0
WARD              0
X                 0
Y                 0
PRICE         48491
dtype: int64

## Pre-processing

One of the most important variables that we will be focusing on later is WARD. Let's take a look to it and see the different values it takes.

In [9]:
# Look at the unique values of WARD
data_df['WARD'].unique()

array(['Ward 2', 'Ward 1', 'Ward 6', 'Ward 5', 'Ward 3', 'Ward 4',
       'Ward 7', 'Ward 8'], dtype=object)

At the moment the values of WARD are string, we would like to transform them to int. How would you do that?

In [10]:
# Transform the WARD values
data_df['WARD'] = data_df['WARD'].apply(lambda x: int(str(x).replace('Ward ', '')))
data_df

/home/jgonzalezlopez/.local/share/virtualenvs/monolith-interview-1MNJPwyq/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NUM_UNITS,ROOMS,BEDRM,BATHRM,HF_BATHRM,KITCHENS,STORIES,HEAT,AC,FIREPLACES,ROOF,EXTWALL,AYB,EYB,YR_SALE,CNDTN,GBA,LANDAREA,WARD,X,Y,PRICE
0,2.0,8,4,4,0,2.0,3.0,Warm Cool,Y,5,Metal- Sms,Common Brick,1910.0,1972,2003.0,3.0,2522.0,1680,2,-77.040429,38.914881,1095000.0
1,2.0,11,5,3,1,2.0,3.0,Warm Cool,Y,4,Built Up,Common Brick,1898.0,1972,2000.0,3.0,2567.0,1680,2,-77.040429,38.914881,NaN
2,2.0,9,5,3,1,2.0,3.0,Hot Water Rad,Y,4,Built Up,Common Brick,1910.0,1984,2016.0,4.0,2522.0,1680,2,-77.040429,38.914881,2100000.0
3,2.0,8,5,3,1,2.0,3.0,Hot Water Rad,Y,3,Built Up,Common Brick,1900.0,1984,2006.0,3.0,2484.0,1680,2,-77.040429,38.914881,1602000.0
4,1.0,11,3,2,1,1.0,3.0,Warm Cool,Y,0,Neopren,Common Brick,1913.0,1985,NaN,3.0,5255.0,2032,2,-77.040429,38.914881,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106672,2.0,8,4,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1962,NaN,2.0,1600.0,6337,8,-77.006347,38.821799,NaN
106673,2.0,10,5,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1962,2012.0,2.0,1600.0,5348,8,-77.006347,38.821799,100000.0
106674,2.0,10,4,2,0,2.0,2.0,Forced Air,N,0,Built Up,Common Brick,1953.0,1953,2009.0,2.0,1600.0,3466,8,-77.006347,38.821799,NaN
106675,2.0,10,4,2,0,2.0,2.0,Forced Air,N,0,Comp Shingle,Common Brick,1953.0,1971,2017.0,3.0,1600.0,3046,8,-77.006347,38.821799,215000.0
106676,2.0,10,4,2,0,2.0,2.0,Forced Air,Y,0,Comp Shingle,Common Brick,1953.0,1971,2017.0,4.0,1600.0,5098,8,-77.006347,38.821799,140000.0

## Save Data

Finally, let's save out results so we can continue using them in the next notebook

In [11]:
data_df.reset_index(drop=True).to_csv(output_data_path, compression='zip')